# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      working-directory: ./packages/nocodb
      id: nvm
    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
        cache: 'npm'
    - name: install dependencies
      working-directory: ./packages/nocodb
      run: npm ci
    - name: run unit tests
      working-directory: ./packages/nocodb
      run: npm run unit-test
    - name: run rest tests
      working-directory: ./packages/nocodb
      run: npm run local:test:unit
